export * from "./IColor";
export * from "./IShape";
export * from "./IDraw";
export * from "./IBoid";
export * from "./IPointThreeD";
export * from "./IPoint";
export * from "./IFlock";
export * from "./IBoidAttractor";
export * from "./IBoidAttractorConfig";