parcelRequire=function(e,r,n,t){var i="function"==typeof parcelRequire&&parcelRequire,o="function"==typeof require&&require;function u(n,t){if(!r[n]){if(!e[n]){var f="function"==typeof parcelRequire&&parcelRequire;if(!t&&f)return f(n,!0);if(i)return i(n,!0);if(o&&"string"==typeof n)return o(n);var c=new Error("Cannot find module '"+n+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[n][1][r]||r},p.cache={};var l=r[n]=new u.Module(n);e[n][0].call(l.exports,p,l,l.exports,this)}return r[n].exports;function p(e){return u(p.resolve(e))}}u.isParcelRequire=!0,u.Module=function(e){this.id=e,this.bundle=u,this.exports={}},u.modules=e,u.cache=r,u.parent=i,u.register=function(r,n){e[r]=[function(e,r){r.exports=n},{}]};for(var f=0;f<n.length;f++)u(n[f]);if(n.length){var c=u(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=c:"function"==typeof define&&define.amd?define(function(){return c}):t&&(this[t]=c)}return u}({"AB0y":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.createCanvas=void 0;var e=function(e){var t,n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:300,i=arguments.length>2&&void 0!==arguments[2]?arguments[2]:300,o=!(arguments.length>3&&void 0!==arguments[3])||arguments[3],l=arguments.length>4&&void 0!==arguments[4]?arguments[4]:null,d=document.querySelector("#".concat(e)),c=d.getBoundingClientRect().width,a=d.getBoundingClientRect().height;if(d){(t=document.createElement("canvas")).width=o?c:n,t.height=o?a:i,t.style.position="relative",t.style.top="0",t.style.left="0",l&&(t.className=l),d.appendChild(t);console.log(o),o&&window.addEventListener("resize",function(e){console.log(e);var n=d.getBoundingClientRect().width,i=d.getBoundingClientRect().height;t.width=n,t.height=i},!0)}return t||null};exports.createCanvas=e;
},{}],"UTAc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.draw=void 0;var e=function(e){var n,r=e,t=function e(){n=requestAnimationFrame(e),r&&r()};requestAnimationFrame(t);return{play:function(){requestAnimationFrame(t)},pause:function(){window.cancelAnimationFrame(n)}}};exports.draw=e;
},{}],"beFE":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.mousePositionListener=void 0;var e=function(e,o){var t=function(e){o(e)};return e.addEventListener("mousemove",t),function(){e.removeEventListener("mousemove",t)}};exports.mousePositionListener=e;
},{}],"QMZd":[function(require,module,exports) {
"use strict";var e=this&&this.__createBinding||(Object.create?function(e,t,r,i){void 0===i&&(i=r),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[r]}})}:function(e,t,r,i){void 0===i&&(i=r),e[i]=t[r]}),t=this&&this.__exportStar||function(t,r){for(var i in t)"default"===i||Object.prototype.hasOwnProperty.call(r,i)||e(r,t,i)};Object.defineProperty(exports,"__esModule",{value:!0}),t(require("./mousePositionListener"),exports);
},{"./mousePositionListener":"beFE"}],"fxNu":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.renderFactory=void 0;var e=require("lib/createCanvas"),r=require("lib/draw"),t=function(t){return function(n){var o=arguments.length>1&&void 0!==arguments[1]?arguments[1]:200,a=arguments.length>2&&void 0!==arguments[2]?arguments[2]:200,i=!(arguments.length>3&&void 0!==arguments[3])||arguments[3],d=arguments.length>4&&void 0!==arguments[4]?arguments[4]:null,l=e.createCanvas(n,o,a,i,d);return r.draw(t(l))}};exports.renderFactory=t;
},{"lib/createCanvas":"AB0y","lib/draw":"UTAc"}],"feMM":[function(require,module,exports) {
"use strict";var e=this&&this.__createBinding||(Object.create?function(e,t,r,i){void 0===i&&(i=r),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[r]}})}:function(e,t,r,i){void 0===i&&(i=r),e[i]=t[r]}),t=this&&this.__exportStar||function(t,r){for(var i in t)"default"===i||Object.prototype.hasOwnProperty.call(r,i)||e(r,t,i)};Object.defineProperty(exports,"__esModule",{value:!0}),t(require("./renderFactory"),exports);
},{"./renderFactory":"fxNu"}],"pj/b":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.simpleMouseTrack=void 0;var e=require("lib/createCanvas"),t=require("lib/draw"),r=require("lib/listeners"),i=function(e){var t=0,i=0,a=e.getContext("2d");return r.mousePositionListener(e,function(e){var r=e.offsetX,a=e.offsetY;i=a,t=r}),function(){var r=e.clientWidth,n=e.clientHeight;a.clearRect(0,0,r,n),a.fillStyle="#000000",a.fillRect(0,0,t,i)}},a=function(r){var a=arguments.length>1&&void 0!==arguments[1]?arguments[1]:900,n=arguments.length>2&&void 0!==arguments[2]?arguments[2]:900,s=e.createCanvas(r,a,n,!0),l=t.draw(i(s));return{pause:l.pause,play:l.play}};exports.simpleMouseTrack=a;
},{"lib/createCanvas":"AB0y","lib/draw":"UTAc","lib/listeners":"QMZd"}],"7QCb":[function(require,module,exports) {
"use strict";var e=this&&this.__createBinding||(Object.create?function(e,r,t,i){void 0===i&&(i=t),Object.defineProperty(e,i,{enumerable:!0,get:function(){return r[t]}})}:function(e,r,t,i){void 0===i&&(i=t),e[i]=r[t]}),r=this&&this.__exportStar||function(r,t){for(var i in r)"default"===i||Object.prototype.hasOwnProperty.call(t,i)||e(t,r,i)};Object.defineProperty(exports,"__esModule",{value:!0}),r(require("lib/createCanvas"),exports),r(require("lib/draw"),exports),r(require("lib/listeners"),exports),r(require("lib/factories"),exports),r(require("./lib/simpleMouseTrack"),exports);
},{"lib/createCanvas":"AB0y","lib/draw":"UTAc","lib/listeners":"QMZd","lib/factories":"feMM","./lib/simpleMouseTrack":"pj/b"}]},{},["7QCb"], "p5-ts-boilerplate")
//# sourceMappingURL=/index.map